### ISSUE TITLE
Error Loading The Script

### ISSUE THREAD

**Issue by MomenFathi** [BornToBeRoot/PowerShell_Get-WLANProfiles#1]
![capture](https://cloud.githubusercontent.com/assets/8422599/13766149/131eb78c-ea68-11e5-96ce-61ad4a3af39b.PNG)

**Comment by BornToBeRoot** [comment]
The script is working fine.  The execution of scripts is disabled by default on all systems (Win 7, 8, etc.), because of security resaons (.ps1-scripts are working different than .cmd or .bat). 

I'll won't help you hacking in other users wifi with this script. This script is only intended to help people who forget their key or to show (for learning purposes) how easy it is to read them.

For more details about ececution scripts on your system:
[Technet Set-ExecutionPolicy](https://technet.microsoft.com/en-us/library/hh849812.aspx)

Greetings
BornToBeRoot

**Comment by MomenFathi** [comment]
I am trying to run it on my own PC :| not hacking into any body -_ !!

**Comment by BornToBeRoot** [comment]
Is this script working now on your pc?

If it is the same error message, as shown in the screenshot. Start your **PowerShell as Administrator** and type the following command `Set-ExecutionPolicy Unrestricted`
